apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::460840353653:role/cluster-1-dev-cluster-20250921203804150200000002
      username: admin
      groups:
        - system:masters
  mapUsers: |
    - userarn: arn:aws:iam::460840353653:user/Fares
      username: fares
      groups:
        - system:masters
